target: all

multitenancy_enabled: false

common:
  storage:
    backend: s3
    s3:
      region: ${S3_REGION}
      endpoint: ${S3_ENDPOINT}
      bucket_name: ${S3_BUCKET_NAME}
      access_key_id: ${S3_ACCESS_KEY_ID}
      secret_access_key: ${S3_SECRET_ACCESS_KEY}

server:
  grpc_listen_address: '::'

blocks_storage:
  storage_prefix: blocks
  tsdb:
    dir: /data/ingester
    retention_period: 24h

distributor:
  ring:
    kvstore:
      store: consul
      prefix: ${CONSUL_PREFIX}
      consul:
        host: ${CONSUL_URL}
        acl_token: ${CONSUL_TOKEN}
    instance_addr: "${FLY_ALLOC_ID}.vm.${FLY_APP_NAME}.internal"

ingester:
  ring:
    kvstore:
      store: consul
      prefix: ${CONSUL_PREFIX}
      consul:
        host: ${CONSUL_URL}
        acl_token: ${CONSUL_TOKEN}
    instance_availability_zone: ${FLY_REGION}
    instance_addr: "${FLY_ALLOC_ID}.vm.${FLY_APP_NAME}.internal"

compactor:
  sharding_ring:
    kvstore:
      store: consul
      prefix: ${CONSUL_PREFIX}
      consul:
        host: ${CONSUL_URL}
        acl_token: ${CONSUL_TOKEN}
    instance_addr: "${FLY_ALLOC_ID}.vm.${FLY_APP_NAME}.internal"

store_gateway:
  sharding_ring:
    kvstore:
      store: consul
      prefix: ${CONSUL_PREFIX}
      consul:
        host: ${CONSUL_URL}
        acl_token: ${CONSUL_TOKEN}
    instance_availability_zone: ${FLY_REGION}
    instance_addr: "${FLY_ALLOC_ID}.vm.${FLY_APP_NAME}.internal"
